[project]
name = "cc_pixi"
version = "0.1.0"
description = "Add a short description here"
authors = ["Robin Beer <r.beer@outlook.de>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
